### ISSUE TITLE
Fatal error:database error:SQL state [hy000][1045] access denied for user 'root'@localhost ' using password no

### ISSUE THREAD

**Issue by hulkiii** [Riadz/E-commerce#2]
![16558759659524626373992800844189](https://user-images.githubusercontent.com/72141287/174951081-6e3f6a5f-f9b8-4ffd-b2f3-3afd90f6e228.jpg)
![Uploading 16558759974428707882592063613478.jpg…]()

**Comment by Riadz** [comment]
@hulkiii sorry for the late reply 😅 but i never intended to maintain this project,
anyways from the error seems like your SQL database credentials are wrong, 
inputting the correct credentials should resolve the issue.
